name: Build and Deploy Docker Image

# Run this workflow on push to the main branch, but only if HTML files change
on:
  push:
    branches:
      - master
    paths:
      - '**/*.html'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to access the files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker Buildx (optional, for multi-architecture builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (you need to set up secrets for DOCKERHUB_USERNAME and DOCKERHUB_TOKEN in your repo settings)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/newstaticone:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/newstaticone:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Docker container
        run: |
         # Pull the latest image and run it
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/https://github.com/Lewie12/StaticOne.git
          docker stop staticone || true
          docker rm staticone || true
          docker run -d -p 8080:80 --name staticone ${{ secrets.DOCKERHUB_USERNAME }}/newstaticone:latest
