name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**/*.html'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/newstaticone:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/newstaticone:latest

      - name: Deploy Docker container on EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ec2-user
        run: |
          # Create a temporary SSH key file
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Add EC2 to known hosts
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Connect to the EC2 instance and pull the latest Docker image
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/newstaticone:latest
            docker stop staticone || true
            docker rm staticone || true
            docker run -d -p 8080:80 --name staticone ${{ secrets.DOCKERHUB_USERNAME }}/newstaticone:latest
          EOF

          # Clean up
          rm private_key.pem
